# Generated by Django 5.1.1 on 2024-11-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patientdetails_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
